In [1]:
# ch01
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,8))
print("size: {} bytes".format(Z.size))
print("itemsize: {} bytes".format(Z.itemsize))
print("{} bytes".format(Z.size * Z.itemsize))

size: 80 bytes
itemsize: 8 bytes
640 bytes


In [5]:
# %run `sth.py`
! ls
! python3 -c "import numpy; numpy.info(numpy.add);"

README.md   np100.ipynb
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : n

In [6]:
# ch06
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# nonzero，返回array里面的非零元素的索引值数组
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [11]:
# ch11
# 对角矩阵，数量矩阵，单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.80447026 0.23120417 0.56811013]
  [0.46280032 0.12138581 0.32372037]
  [0.27617159 0.52260856 0.07997414]]

 [[0.65445169 0.69585406 0.39994724]
  [0.56306243 0.93065957 0.83790446]
  [0.31069363 0.09549381 0.43484678]]

 [[0.02901398 0.1664131  0.95985693]
  [0.18906658 0.42475841 0.62380199]
  [0.55315948 0.91509301 0.03944147]]]


In [13]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Z)
print(Zmin,Zmax)

[[0.51443379 0.7005365  0.67501082 0.45120614 0.17342438 0.74209164
  0.05918411 0.27322234 0.5081639  0.45401389]
 [0.24497727 0.99963522 0.56678138 0.02466529 0.98274694 0.67656163
  0.4599189  0.17455983 0.04766654 0.62307449]
 [0.35723065 0.28290774 0.34972088 0.13121272 0.376232   0.77220134
  0.15733809 0.4458547  0.98477687 0.5017709 ]
 [0.64795167 0.59466352 0.9745692  0.18040743 0.65262112 0.93478113
  0.26964431 0.13210196 0.72368801 0.82875677]
 [0.43285464 0.91495044 0.54045644 0.54489484 0.49762562 0.525127
  0.185396   0.6081172  0.40477083 0.17221565]
 [0.78099922 0.07276854 0.79280232 0.13165615 0.81744816 0.26806594
  0.73974662 0.7982987  0.48645119 0.60761601]
 [0.16796625 0.35252368 0.16293615 0.74257456 0.81273283 0.06220308
  0.36480519 0.56182485 0.90917907 0.62554356]
 [0.19848904 0.92919884 0.75854641 0.69010597 0.60113949 0.13123795
  0.48577034 0.69156227 0.29997309 0.45514748]
 [0.8866666  0.15729621 0.77465743 0.76083016 0.43148761 0.20489567
  0.50363198 0

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4692050747386999


In [15]:
# Z[1:2,3:4]类似的取矩阵的语法
Z = np.ones((10,10))
print(Z)
# Z[1:-1,1:-1] = 0
Z[1:3,3:5] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# ch16
# pad:垫子,铺路 转一圈，周围围一圈0
# constant,edge,linner_ramp(边缘递减填充),maximum,mean,
# median,minimum,reflect(边缘对称),symmetric,wrap(后面填前面前面填后面)
Z =np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in {np.nan}) #!!! True
print(0.3 == 3 * 0.1) #!!! False

nan
False
False
nan
True
False


In [18]:
# 生成方阵，对角线元素向左下角移动几位
Z = np.diag(1+np.arange(4),k=-2)
print(Z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [19]:
# checkboard 棋盘...
Z = np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2] = 1
print(Z)
Z[::2,1::2] = 2
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]


In [20]:
# 从0往后递增的序列数，前面的indices的数在该array里面的索引位置
# Z = np.unravel_index(indices=[22, 41, 37], shape=(7,6))
# (array([3, 6, 6]), array([4, 5, 1]))
Z = np.unravel_index(100,(6,7,8))
print(Z)

(1, 5, 4)


In [21]:
#ch21
# tile:铺，重复整个数组后面shape的次数
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
# 标准化(归一化)一个数组
Z = np.random.random((5,5))
print(Z)
Z = (Z-np.mean(Z))/(np.std(Z))
print(Z)

[[0.59139023 0.43099564 0.39567925 0.61624902 0.57708021]
 [0.54418498 0.17427999 0.9939781  0.30649972 0.75579663]
 [0.09074791 0.87639026 0.63480892 0.9820696  0.85602324]
 [0.70120417 0.02222665 0.70773573 0.61797744 0.20011985]
 [0.49543662 0.18362604 0.79107243 0.73538157 0.09921224]]
[[ 0.20012051 -0.37118969 -0.49698328  0.28866516  0.1491496 ]
 [ 0.03197993 -1.28558629  1.6341     -0.81463225  0.78572038]
 [-1.58311955  1.21526335  0.35477374  1.59168308  1.14271798]
 [ 0.59126728 -1.82718573  0.61453205  0.29482161 -1.19354718]
 [-0.14165706 -1.25229652  0.91136942  0.71300391 -1.55297044]]


In [23]:
# 自定义数据类型
color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),
                  ('b',np.ubyte,1),('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [24]:
# 矩阵乘法
X = np.ones((5,3))
Y = np.ones((3,2))
Z = np.dot(X,Y)
Z2 = X @ Y
print(Z)
print(Z2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
# 条件选择
Z = np.arange(11)
Z[(3<Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#ch26
# 自带的sum的-1指的是求和的初始值，np.sum的-1指的是axis，轴的概念 
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [27]:
Z = np.array([1,2,3])
print(Z ** Z) # 矩阵中对应的各个元素的乘方
print(2 << Z >> 2) #左移两位再右移两位
print(Z < -Z) #挨个元素的比较
print(1j * Z) #矩阵可以进行虚数运算
print(Z/1/1)
# print(Z<Z>Z) #真假值和矩阵不能比较大小

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


In [28]:
print(np.array(0)/np.array(0))   # 真除法返回nan
print(np.array(0)//np.array(0)) # 地板触发返回0
print(np.array([np.nan]))
print(np.array([np.nan]).astype(int)) #nan as_int 会返回最小的int64位带符号整形数-9223372036854775808
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[nan]
[-9223372036854775808]
[-9.22337204e+18]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [30]:
# uniform: [-10,10)左闭右开，均匀取样取10个
# ceil: 天花板，取上界
# copysign: 把第二个参数的符号赋值给第一个
Z = np.random.uniform(-10,10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-9.63384438  7.19863745 -4.73063125 -0.42450219  4.18795861  7.85737354
 -9.48583729 -5.43215291 -1.22539101  8.69126188]
[-10.   8.  -5.  -1.   5.   8. -10.  -6.  -2.   9.]


In [33]:
# intersect 取交集，排序之后找两个集合都有的元素
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)
print(np.intersect1d(Z1,Z2))

[5 3 4 7 6 5 6 6 1 5] [1 5 7 0 8 8 6 0 0 3]
[1 3 5 6 7]


In [40]:
# ch31
# 忽略numpy的全部警告
# defaults = np.seterr(all='ignore')
Z = np.ones(1)/0
# 返回正常mode
# _ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    X = np.ones(1)/0
    print(X)

AttributeError: module 'numpy' has no attribute 'errstatde'

In [43]:
b = np.sqrt(-1) == np.emath.sqrt(-1) 
print(np.sqrt(-1)) # nan
print(np.emath.sqrt(-1)) //1j
print(b)

nan
1j
False


In [49]:
# 时间运算
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday,today,tomorrow)

2019-05-07 2019-05-08 2019-05-09


In [57]:
# 获取按天增加的固定日期
Z = np.arange('2019-04','2019-05',dtype='datetime64[D]')
print(Z)

['2019-04-01' '2019-04-02' '2019-04-03' '2019-04-04' '2019-04-05'
 '2019-04-06' '2019-04-07' '2019-04-08' '2019-04-09' '2019-04-10'
 '2019-04-11' '2019-04-12' '2019-04-13' '2019-04-14' '2019-04-15'
 '2019-04-16' '2019-04-17' '2019-04-18' '2019-04-19' '2019-04-20'
 '2019-04-21' '2019-04-22' '2019-04-23' '2019-04-24' '2019-04-25'
 '2019-04-26' '2019-04-27' '2019-04-28' '2019-04-29' '2019-04-30']


In [60]:
# 矩阵运算
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
print(B)
np.divide(A,2,out=A)
print(A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-1.5 -1.5 -1.5]


In [ ]:
#ch36