In [2]:
# ch01
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,8))
print("size: {} bytes".format(Z.size))
print("itemsize: {} bytes".format(Z.itemsize))
print("{} bytes".format(Z.size * Z.itemsize))

size: 80 bytes
itemsize: 8 bytes
640 bytes


In [5]:
# %run `sth.py`
! ls
! python3 -c "import numpy; numpy.info(numpy.add);"

README.md   np100.ipynb
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : n

In [6]:
# ch06
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# nonzero，返回array里面的非零元素的索引值数组
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [11]:
# ch11
# 对角矩阵，数量矩阵，单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.80447026 0.23120417 0.56811013]
  [0.46280032 0.12138581 0.32372037]
  [0.27617159 0.52260856 0.07997414]]

 [[0.65445169 0.69585406 0.39994724]
  [0.56306243 0.93065957 0.83790446]
  [0.31069363 0.09549381 0.43484678]]

 [[0.02901398 0.1664131  0.95985693]
  [0.18906658 0.42475841 0.62380199]
  [0.55315948 0.91509301 0.03944147]]]


In [13]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Z)
print(Zmin,Zmax)

[[0.51443379 0.7005365  0.67501082 0.45120614 0.17342438 0.74209164
  0.05918411 0.27322234 0.5081639  0.45401389]
 [0.24497727 0.99963522 0.56678138 0.02466529 0.98274694 0.67656163
  0.4599189  0.17455983 0.04766654 0.62307449]
 [0.35723065 0.28290774 0.34972088 0.13121272 0.376232   0.77220134
  0.15733809 0.4458547  0.98477687 0.5017709 ]
 [0.64795167 0.59466352 0.9745692  0.18040743 0.65262112 0.93478113
  0.26964431 0.13210196 0.72368801 0.82875677]
 [0.43285464 0.91495044 0.54045644 0.54489484 0.49762562 0.525127
  0.185396   0.6081172  0.40477083 0.17221565]
 [0.78099922 0.07276854 0.79280232 0.13165615 0.81744816 0.26806594
  0.73974662 0.7982987  0.48645119 0.60761601]
 [0.16796625 0.35252368 0.16293615 0.74257456 0.81273283 0.06220308
  0.36480519 0.56182485 0.90917907 0.62554356]
 [0.19848904 0.92919884 0.75854641 0.69010597 0.60113949 0.13123795
  0.48577034 0.69156227 0.29997309 0.45514748]
 [0.8866666  0.15729621 0.77465743 0.76083016 0.43148761 0.20489567
  0.50363198 0

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4692050747386999


In [15]:
# Z[1:2,3:4]类似的取矩阵的语法
Z = np.ones((10,10))
print(Z)
# Z[1:-1,1:-1] = 0
Z[1:3,3:5] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# ch16
# pad:垫子,铺路 转一圈，周围围一圈0
# constant,edge,linner_ramp(边缘递减填充),maximum,mean,
# median,minimum,reflect(边缘对称),symmetric,wrap(后面填前面前面填后面)
Z =np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in {np.nan}) #!!! True
print(0.3 == 3 * 0.1) #!!! False

nan
False
False
nan
True
False


In [18]:
# 生成方阵，对角线元素向左下角移动几位
Z = np.diag(1+np.arange(4),k=-2)
print(Z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [19]:
# checkboard 棋盘...
Z = np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2] = 1
print(Z)
Z[::2,1::2] = 2
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]


In [20]:
# 从0往后递增的序列数，前面的indices的数在该array里面的索引位置
# Z = np.unravel_index(indices=[22, 41, 37], shape=(7,6))
# (array([3, 6, 6]), array([4, 5, 1]))
Z = np.unravel_index(100,(6,7,8))
print(Z)

(1, 5, 4)


In [21]:
#ch21
# tile:铺，重复整个数组后面shape的次数
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
# 标准化(归一化)一个数组
Z = np.random.random((5,5))
print(Z)
Z = (Z-np.mean(Z))/(np.std(Z))
print(Z)

[[0.59139023 0.43099564 0.39567925 0.61624902 0.57708021]
 [0.54418498 0.17427999 0.9939781  0.30649972 0.75579663]
 [0.09074791 0.87639026 0.63480892 0.9820696  0.85602324]
 [0.70120417 0.02222665 0.70773573 0.61797744 0.20011985]
 [0.49543662 0.18362604 0.79107243 0.73538157 0.09921224]]
[[ 0.20012051 -0.37118969 -0.49698328  0.28866516  0.1491496 ]
 [ 0.03197993 -1.28558629  1.6341     -0.81463225  0.78572038]
 [-1.58311955  1.21526335  0.35477374  1.59168308  1.14271798]
 [ 0.59126728 -1.82718573  0.61453205  0.29482161 -1.19354718]
 [-0.14165706 -1.25229652  0.91136942  0.71300391 -1.55297044]]


In [23]:
# 自定义数据类型
color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),
                  ('b',np.ubyte,1),('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [24]:
# 矩阵乘法
X = np.ones((5,3))
Y = np.ones((3,2))
Z = np.dot(X,Y)
Z2 = X @ Y
print(Z)
print(Z2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
# 条件选择
Z = np.arange(11)
Z[(3<Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#ch26
# 自带的sum的-1指的是求和的初始值，np.sum的-1指的是axis，轴的概念 
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [27]:
Z = np.array([1,2,3])
print(Z ** Z) # 矩阵中对应的各个元素的乘方
print(2 << Z >> 2) #左移两位再右移两位
print(Z < -Z) #挨个元素的比较
print(1j * Z) #矩阵可以进行虚数运算
print(Z/1/1)
# print(Z<Z>Z) #真假值和矩阵不能比较大小

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


In [28]:
print(np.array(0)/np.array(0))   # 真除法返回nan
print(np.array(0)//np.array(0)) # 地板触发返回0
print(np.array([np.nan]))
print(np.array([np.nan]).astype(int)) #nan as_int 会返回最小的int64位带符号整形数-9223372036854775808
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[nan]
[-9223372036854775808]
[-9.22337204e+18]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [30]:
# uniform: [-10,10)左闭右开，均匀取样取10个
# ceil: 天花板，取上界
# copysign: 把第二个参数的符号赋值给第一个
Z = np.random.uniform(-10,10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-9.63384438  7.19863745 -4.73063125 -0.42450219  4.18795861  7.85737354
 -9.48583729 -5.43215291 -1.22539101  8.69126188]
[-10.   8.  -5.  -1.   5.   8. -10.  -6.  -2.   9.]


In [33]:
# intersect 取交集，排序之后找两个集合都有的元素
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)
print(np.intersect1d(Z1,Z2))

[5 3 4 7 6 5 6 6 1 5] [1 5 7 0 8 8 6 0 0 3]
[1 3 5 6 7]


In [3]:
# ch31
# 忽略numpy的全部警告
# defaults = np.seterr(all='ignore')
Z = np.ones(1)/0
# 返回正常mode
# _ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    X = np.ones(1)/0
    print(X)

[inf]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [43]:
b = np.sqrt(-1) == np.emath.sqrt(-1) 
print(np.sqrt(-1)) # nan
print(np.emath.sqrt(-1)) //1j
print(b)

nan
1j
False


In [49]:
# 时间运算
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday,today,tomorrow)

2019-05-07 2019-05-08 2019-05-09


In [57]:
# 获取按天增加的固定日期
Z = np.arange('2019-04','2019-05',dtype='datetime64[D]')
print(Z)

['2019-04-01' '2019-04-02' '2019-04-03' '2019-04-04' '2019-04-05'
 '2019-04-06' '2019-04-07' '2019-04-08' '2019-04-09' '2019-04-10'
 '2019-04-11' '2019-04-12' '2019-04-13' '2019-04-14' '2019-04-15'
 '2019-04-16' '2019-04-17' '2019-04-18' '2019-04-19' '2019-04-20'
 '2019-04-21' '2019-04-22' '2019-04-23' '2019-04-24' '2019-04-25'
 '2019-04-26' '2019-04-27' '2019-04-28' '2019-04-29' '2019-04-30']


In [60]:
# 矩阵运算
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
print(B)
np.divide(A,2,out=A)
print(A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-1.5 -1.5 -1.5]


In [5]:
#ch36
#trunc: 丢弃小数部分
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[-0.78553857 -2.07241219 -2.81977071  9.38619493  6.27772561  1.77703609
 -2.38792907  4.89226792 -6.00975611  8.66366847]
[-1. -3. -3.  9.  6.  1. -3.  4. -7.  8.]
[-1. -3. -3.  9.  6.  1. -3.  4. -7.  8.]
[-1. -3. -3.  9.  6.  1. -3.  4. -7.  8.]
[ 0 -2 -2  9  6  1 -2  4 -6  8]
[-0. -2. -2.  9.  6.  1. -2.  4. -6.  8.]


In [7]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [9]:
# np中的生成器
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
# 均等分布
Z = np.linspace(0,1,11,endpoint=False)
# Z = np.linspace(0,1,11)
print(Z)
# print(Z[1:])
Z2 = np.linspace(0,1,12)
print(Z2)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [17]:
# 排序
Z = np.random.random(10)
Z.sort()
print(Z)

[0.16875041 0.27243088 0.27952839 0.64312306 0.65242013 0.67212811
 0.72674113 0.7380938  0.81604254 0.86876223]


In [18]:
# ch41
# 使用reduce加和
Z = np.arange(10)
S = np.add.reduce(Z)
print(S)

45


In [23]:
# allclose: 大体相等，都特别相近
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
A = np.array([0,1,2])
B = np.array([0,1,1.999999999])
print(A,B)

equal1 = np.allclose(A,B)
equal2 = np.array_equal(A,B)
print(equal1,equal2)

[0 1 2] [0. 1. 2.]
True False


In [26]:
# 创建不可变的矩阵
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

In [28]:
# 笛卡尔坐标转化为极坐标，半径和弧度值
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.06857167 0.5439474 ]
 [0.58206486 0.33818572]
 [0.27146536 0.41223657]
 [0.84725328 0.8331458 ]
 [0.16610036 0.2720234 ]
 [0.78222799 0.04856938]
 [0.22350577 0.43741411]
 [0.03127044 0.73824175]
 [0.01785389 0.70183256]
 [0.39558987 0.7621185 ]]
[0.54825254 0.67317835 0.49359136 1.18826346 0.31872569 0.7837344
 0.49120865 0.73890373 0.70205961 0.85867104]
[1.44539477 0.52633951 0.98845607 0.77700304 1.02261146 0.06201147
 1.09841077 1.52846364 1.54536286 1.09201244]


In [30]:
# 把矩阵的最大值替换为0
# argmax: 最大的元素
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.57431926 0.19841075 0.17932772 0.73909108 0.69344201 0.28109883
 0.33887888 0.40279865 0.71104443 0.61327162]
[0.57431926 0.19841075 0.17932772 0.         0.69344201 0.28109883
 0.33887888 0.40279865 0.71104443 0.61327162]


In [39]:
# ch46
# meshgrid, 二维网格
Z = np.zeros((5,5),[('x',float),('y',float)])
# print(Z)
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)
print(Z['x'])
print(Z['y'])

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [41]:
# 计算高斯矩阵，Cij=1/(xi-yj)
# linalg=linear+algebra, np.linalg是线性计算的模块
X = np.arange(8)
Y = X + 0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [43]:
# eps: 精度
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [56]:
# 打印所有的值而不是缩写
Z = np.ones((256,256))
# print(Z)
import sys
# np.set_printoptions(threshold=np.nan)
# np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=sys.maxsize)
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [50]:
# 找到两个向量最接近的那个值
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z,v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2 ... 97 98 99] 47.91000258492372
48


In [52]:
# ch51
Z = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),
    ('color',[('r',float,1),('g',float,1),('b',float,1)])
])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [61]:
# 两个坐标各个点之间的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
# print(X,Y)
print(X.shape,X.T.shape)
print(X-X.T)
# print(D)

import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
# print(D)

(1, 10) (10, 1)
[[ 0.         -0.96524257 -0.65516101 -0.31287757 -0.29193537 -0.82321357
  -0.8923433  -0.13899344  0.00117766 -0.3693485 ]
 [ 0.96524257  0.          0.31008156  0.65236501  0.67330721  0.14202901
   0.07289927  0.82624914  0.96642024  0.59589407]
 [ 0.65516101 -0.31008156  0.          0.34228344  0.36322565 -0.16805256
  -0.23718229  0.51616758  0.65633867  0.28581251]
 [ 0.31287757 -0.65236501 -0.34228344  0.          0.0209422  -0.510336
  -0.57946573  0.17388413  0.31405523 -0.05647094]
 [ 0.29193537 -0.67330721 -0.36322565 -0.0209422   0.         -0.5312782
  -0.60040794  0.15294193  0.29311303 -0.07741314]
 [ 0.82321357 -0.14202901  0.16805256  0.510336    0.5312782   0.
  -0.06912973  0.68422013  0.82439123  0.45386507]
 [ 0.8923433  -0.07289927  0.23718229  0.57946573  0.60040794  0.06912973
   0.          0.75334987  0.89352096  0.5229948 ]
 [ 0.13899344 -0.82624914 -0.51616758 -0.17388413 -0.15294193 -0.68422013
  -0.75334987  0.          0.1401711  -0.23035

In [62]:
# float转化为int
Z = np.arange(10,dtype=np.float32)
Z = Z.astype(np.int32,copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
# 从string里面读取矩阵
# 没有的值使用的是-1代替
from io import StringIO
s = StringIO("""1,2,3,4,5\n6, , ,7,8\n , ,9,10,11\n""")
Z = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [65]:
# enumerate 矩阵
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [67]:
# 符合高斯分布的矩阵
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
print(X,Y)
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0,0.0
G = np.exp(- ((D-mu)**2/(2.0*sigma**2)))
print(G)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [69]:
# 随机把一个值放到二维数组里
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [70]:
# 矩阵的每一行减去一个平均数
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True)
# Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[-0.50531534  0.22893165  0.00982275 -0.37083227  0.36060697  0.46088823
   0.36891971  0.18346722 -0.39821216 -0.33827678]
 [-0.06289922  0.39661739 -0.4646281   0.27451432 -0.05571716 -0.20946491
   0.33152168 -0.25290208  0.09267991 -0.04972183]
 [-0.33953339 -0.41580883  0.27521248 -0.35708212  0.13728474  0.00376369
   0.52665302  0.45386142 -0.11223963 -0.1721114 ]
 [-0.04926822  0.36118129  0.25948981  0.20455783  0.43608653 -0.30977055
  -0.21291136 -0.42930168 -0.12804104 -0.13202261]
 [ 0.15493621  0.30468575 -0.56188719  0.18580547 -0.10483517  0.30927129
   0.03018079 -0.19041447 -0.15365015  0.02590747]]


In [72]:
# 根据矩阵的某一行排序
# argsort: 排好序的对应的索引值
Z = np.random.randint(0,10,(3,3))
print(Z)
a = Z[:,1].argsort()
print(a)
print(Z[a])

[[3 9 4]
 [7 2 3]
 [3 6 0]]
[1 2 0]
[[7 2 3]
 [3 6 0]
 [3 9 4]]


In [73]:
# 判断一个矩阵有没有null的行
# any: 有没有其中任一满足条件的行
Z = np.random.randint(0,3,[3,10])
print(Z)
print(Z.any(axis=0))
print(~Z.any(axis=0))
print((~Z.any(axis=0)).any())

[[0 2 2 2 1 1 1 2 1 1]
 [0 1 1 0 2 0 2 1 0 1]
 [0 2 2 2 1 2 1 1 1 2]]
[False  True  True  True  True  True  True  True  True  True]
[ True False False False False False False False False False]
True


In [75]:
# 找到列表里面距离给定的val距离最近的
# flat: 将数据转化为1维的迭代器
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

[0.36522431 0.40821031 0.84087408 0.04273691 0.70207071 0.60133297
 0.96576998 0.26462397 0.90244113 0.3078521 ]
0.40821030513376544


In [76]:
# 使用迭代器计算两个向量的和
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...]=x+y
print(A,B)
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [78]:
# 创建一个有名字的numpy数组
class NamedArray(np.ndarray):
    def __new__(cls,array,name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None:
            return
        self.info = getattr(obj,'name','no name')

Z = NamedArray(np.arange(10),'range_10')
print(Z)
print(Z.name)

[0 1 2 3 4 5 6 7 8 9]
range_10


In [ ]:
#  todo the HARD to be continue。。。
# （也就是说，可能以后hard的这些代码不会写了，至少最近不会再写咯[皱眉]）